import 'model/category.dart';
import 'model/kandidat.dart';

const CATEGORIES_DUMMY_DATA = const [
  Category(
    id: 'P1',
    title: 'BEMU',
    description: '(Badan Eksekutif Mahasiswa Tingkat Universitas)',
    image: 'assets/bemu.png',
  ),
  Category(
    id: 'P2',
    title: 'BEMFA',
    description: '(Badan Eksekutif Mahasiswa Tingkat Fakultas)',
    image: 'assets/bemfa.png',
  ),
  Category(
    id: 'P3',
    title: 'SEMU',
    description: '(Senat Mahasiswa Universitas',
    image: 'assets/semu.png',
  ),
  Category(
    id: 'P4',
    title: 'SEFA',
    description: '(Senat Mahasiswa Fakultas)',
    image: 'assets/senatft.png',
  ),
  Category(
    id: 'P5',
    title: 'HMJ',
    description: '(Himpunan Mahasiswa Jurusan',
    image: 'assets/hmif.jpg',
  )
];

const KANDIDAT_DUMMY_DATA = const [
  Kandidat(
    id: 'C1',
    name: 'Hartanto Santoso',
    partai: 'Partai A',
    jabatan: 'Calon Ketua BEMU',
    image: 'https://krs.umm.ac.id/Poto/2015/201510370311137.JPG',
    category: 'P1',
    suara: 60,
  ),
  Kandidat(
    id: 'C2',
    name: 'Azzam naufal',
    partai: 'Partai B',
    jabatan: 'Calon Ketua BEMU',
    image: 'https://krs.umm.ac.id/Poto/2015/201510370311124.JPG',
    category: 'P1',
    suara: 300,
  ),
  Kandidat(
    id: 'C3',
    name: 'Kiki afs',
    partai: 'Partai z',
    jabatan: 'Calon Ketua BEMU',
    image: 'https://krs.umm.ac.id/Poto/2015/201510370311116.JPG',
    category: 'P1',
    suara: 30,
  ),
  Kandidat(
    id: 'C4',
    name: 'Wahyu Reanaldy',
    partai: 'Partai x',
    jabatan: 'Calon Ketua BEMU',
    image: 'https://krs.umm.ac.id/Poto/2015/201510370311114.JPG',
    category: 'P1',
    suara: 90,
  ),
  Kandidat(
    id: 'C5',
    name: 'Danil Fajar',
    partai: 'Partai x',
    jabatan: 'Calon Ketua BEMU',
    image: 'https://krs.umm.ac.id/Poto/2015/201510370311141.JPG',
    category: 'P1',
    suara: 10,
  ),
  Kandidat(
    id: 'C6',
    name: 'Linggar bagas',
    partai: 'Partai x',
    jabatan: 'Calon Ketua BEMU',
    image: 'https://krs.umm.ac.id/Poto/2015/201510370311145.JPG',
    category: 'P1',
    suara: 10,
  ),
  Kandidat(
    id: 'C7',
    name: 'Multohadi H.',
    partai: 'Partai A',
    jabatan: 'Calon Ketua BEMFA',
    image: 'https://krs.umm.ac.id/Poto/2015/201510370311127.JPG',
    category: 'P2',
    suara: 30,
  ),
  Kandidat(
    id: 'C8',
    name: 'Rian Febriansah',
    partai: 'Partai A',
    jabatan: 'Calon Ketua BEMFA',
    image: 'https://krs.umm.ac.id/Poto/2015/201510370311133.JPG',
    category: 'P2',
    suara: 90,
  ),
  Kandidat(
    id: 'C9',
    name: 'Andika Saifuddin',
    partai: 'Partai V',
    jabatan: 'Calon Ketua BEMFA',
    image: 'https://krs.umm.ac.id/Poto/2015/201510370311138.JPG',
    category: 'P2',
    suara: 90,
  ),
  Kandidat(
    id: 'C10',
    name: 'Handi Pramanda',
    partai: 'Partai V',
    jabatan: 'Calon Ketua BEMFA',
    image: 'https://krs.umm.ac.id/Poto/2015/201510370311140.JPG',
    category: 'P2',
    suara: 90,
  ),
  Kandidat(
    id: 'C11',
    name: 'Auladotoma avicenna',
    partai: 'Partai V',
    jabatan: 'Calon Ketua BEMFA',
    image: 'https://krs.umm.ac.id/Poto/2015/201510370311146.JPG',
    category: 'P2',
    suara: 90,
  ),
  Kandidat(
    id: 'C12',
    name: 'Rizky fuady',
    partai: 'Partai V',
    jabatan: 'Calon Ketua BEMFA',
    image: 'https://krs.umm.ac.id/Poto/2015/201510370311147.JPG',
    category: 'P2',
    suara: 90,
  ),
  Kandidat(
    id: 'C14',
    name: 'Rafli',
    partai: 'Partai V',
    jabatan: 'Calon Ketua SEMU',
    image: 'https://krs.umm.ac.id/Poto/2015/201510370311111.JPG',
    category: 'P3',
    suara: 90,
  ),
  Kandidat(
    id: 'C13',
    name: 'Firdaus nur',
    partai: 'Partai V',
    jabatan: 'Calon Ketua SEMU',
    image: 'https://krs.umm.ac.id/Poto/2015/201510370311110.JPG',
    category: 'P3',
    suara: 90,
  ),
];
